routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'WelcomeController@index');

Route::resource('/articles', 'ArticlesController');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('mail', function() {
	$article = App\Article::with('user')->find(1);

	return Mail::send(
		'emails.articles.created',
		compact('article'),
		function($message) use ($article) {
			$message->to('rudalson@gmail.com');
			$message->subject('새 글이 등록되었습니다 -'.$article->title);
		}

	);
});

Route::get('markdown', function() {
	$text =<<<EOT
# 마크다운 예제 1

이 문서는 [마크다운][1]으로 썼습니다. 화면에는 HTML로 변환되어 출력됩니다.

## 순서 없는 목록

- 첫 번째 항목
- 두 번재 항목[^1]

[1]: http://daringfireball.net/projects/markdown


[^1]: 두 번째 항목_ http://google.com
EOT;

	return app(ParsedownExtra::class)->text($text);
});

Route::get('docs/{file?}', 'DocsController@show');

Route::get('docs/images/{image}', 'DocsController@image')
	->where('image', '[\pL-\pN\._-]+-img-[0-9]{2}.png');

// Event::listen('article.created', function($article) {
// 	var_dump('이벤트를 받았습니다. 받은 데이터(상태)는 다음과 같습니다.');
// 	var_dump($article->toArray());
// });

// DB::listen(function ($query) {
// 	var_dump($query->sql);
// });

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = ['title', 'content'];

    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    public function tags()
    {
    	return $this->belongsToMany(Tag::class);
    }
}

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    public $timestamps = false;
    protected $fillable = ['email', 'password'];
}

app/Documentation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use File;

class Documentation extends Model
{
	public function get($file = 'documentation.md')
	{
		$content = File::get($this->path($file));

		return $this->replaceLinks($content);
	}

	public function image($file)
	{
		return \Image::make($this->path($file, 'docs/images'));
	}

	public function etag($file)
	{
		$lastModified = File::lastModified($this->path($file, 'docs/images'));

		return md5($file . $lastModified);
	}

	protected function path($file, $dir = 'docs')
	{
		$file = ends_with($file, ['.md', '.png']) ? $file : $file . '.md';
		$path = base_path($dir . DIRECTORY_SEPARATOR . $file);

		if (!File::exists($path)) {
			abort(404, '');
		}

		return $path;
	}

	protected function replaceLinks($content)
	{
		return str_replace('/docs/{{version}}', '/docs', $content);
	}
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public $timestamps = false;
    protected $fillable = ['title', 'body'];
}

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name', 'slug'];

    public function articles()
    {
    	return $this->belongsToMany(Article::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = ['last_login'];

    public function articles()
    {
        return $this->hasMany(Article::class);
    }
}

app/helpers.php
<?php

if (! function_exists('markdown')) {
	function markdown($text = null)
	{
		return app(ParsedownExtra::class)->text($text);
	}
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ArticlesController extends Controller
{
    public function index()
    {
    	$articles = \App\Article::latest()->with('user')->paginate(3);

    	return view('articles.index', compact('articles'));
    }

    public function create()
    {
    	return view('articles.create');
    }

    public function store(\App\Http\Requests\ArticlesRequest $request)
    {
    	$article = \App\User::find(1)->articles()->create($request->all());

    	if (!$article) {
    		return back()->with('flash_message', '글이 저장되지 않았습니다.')
    			->withInput();
    	}

    	event(new \App\Events\ArticleCreated($article));

    	return redirect(route('articles.index'))
    		->with('flash_message', '작성하신 글이 저장되었습니다.');
    }

    public function show($id)
    {
    	$article = \App\Article::findOrFail($id);
        debug($article->toArray());

    	// return view('articles.show', compact('article'));
        return $article->toArray();
    }

    public function edit($id)
    {
    	return __METHOD__ . ' id = '. $id;
    }

    public function update(Request $request, $id)
    {
    	return __METHOD__ . 'id = '. $id;
    }

    public function destroy($id)
    {
    	return __METHOD__ . ' id = '. $id;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DocsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DocsController extends Controller
{
    protected $docs;

    public function __construct(\App\Documentation $docs)
    {
    	$this->docs = $docs;
    }

    public function show($file = null)
    {
        $index = \Cache::remember('docs.index', 120, function() {
            return markdown($this->docs->get());
        });

        $content = \Cache::remember("docs.{$file}", 120, function() use ($file) {
            return markdown($this->docs->get($file ?: 'installation.md'));
        });
        // $index = markdown($this->docs->get());
        // $content = markdown($this->docs->get($file ?: 'installation.md'));

    	return view('docs.show', compact('index', 'content'));
    }

    public function image($file)
    {
        $reqEtag = \Request::getEtags();
        $genEtag = $this->docs->etag($file);

        if (isset($reqEtag[0])) {
            if ($reqEtag[0] === $genEtag) {
                return response('', 304);
            }
        }

        $image = $this->docs->image($file);

        return response($image->encode('png'), 200, [
            'Content-Type' => 'image/png',
            'Cache-Control' => 'public, max-age=0',
            'Etag' => $genEtag,
        ]);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class WelcomeController extends Controller
{
    public function index()
    {
    	return view('welcome2');
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<h1>새 포럼 글 쓰기</h1>
		<hr/>

		<form action="{{ route('articles.store') }}" method="POST">
			{!! csrf_field() !!}

			<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
				<label for="title">제목</label>
				<input type="text" name="title" id="title" value="{{ old('title') }}" class="form-control"/>
			</div>

			<div class="form-group {{ $errors->has('content') ? 'has-error' : '' }}">
				<label for="content">본문</label>
				<textarea name="content" id="content" rows="10" class="form-control">{{ old('content') }}</textarea>
				{!! $errors->first('content', '<span class="form-error">:message</span>') !!}
			</div>

			<div class="form-group">
				<button type="submit" class="btn btn-primary">
					저장하기
				</button>
			</div>
		</form>
	</div>
@endsection

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<h1>포럼 글 목록</h1>
		<hr/>
		<ul>
			@forelse($articles as $article)
				<li>
					{{ $article->title }}
					<small>
						by {{ $article->user->name }}
					</small>
				</li>
			@empty
				<p>글이 없습니다.</p>
			@endforelse
		</ul>
	</div>

	@if($articles->count())
		<div class="text-center">
			{!! $articles->render() !!}
		</div>
	@endif
@endsection

resources/views/docs/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<header class="page-header">
			<h2>마크다운 뷰어</h2>
		</header>

		<div class="row">
			<div class="col-md-3 docs__sidebar">
				<aside>
					{!! $index !!}
				</aside>
			</div>

			<div class="col-md-9 docs__content">
				<article>
					{!! $content !!}
				</article>
			</div>
		</div>
	</div>
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <!-- <link href="/css/app.css" rel="stylesheet"> -->
    <link href="{{ elixir('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @if(session()->has('flash_message'))
            <div class="alert alert-info" role="alert">
                {{ session('flash_message') }}
            </div>
        @endif

        @yield('content')
    </div>

    <!-- Scripts -->
    <!-- <script src="/js/app.js"></script> -->
    <script src="{{ elixir('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Laravel Study</title>
</head>
@yield('style')

<body>

@yield('content')

</body>

@yield('script')
</html>

resources/views/partials/footer.blade.php
<footer>
	<p>I'm a footer</p>
</footer>

@section('script')
@parent
	<script>
		alert("I'm a footer's 'script' section");
	</script>
@endsection

resources/views/welcome2.blade.php
@extends('layouts.master')

@section('style')
	<style>
		body {background: green; color:white;}
	</style>
@endsection

@section('content')
	<p>I'm a Child view's 'content' section</p>
	@include('partials.footer')
@endsection

@section('script')
	
	<script>
		alert("I'm a Child view's 'script' section");
	</script>
@endsection